### ISSUE TITLE
Can you write a usage tutorial?

### ISSUE THREAD

**Issue by lihf8515** [yglukhov/webdriver#1]
I used your code and found no output, nor did I start the chrome browser. Here's my code:
```
import asyncdispatch
import chromedriver

type
  LocationStrategy* = enum
    CssSelector,
    LinkTextSelector,
    PartialLinkTextSelector,
    TagNameSelector,
    XPathSelector

proc toKeyword(strategy: LocationStrategy): string =
  case strategy
  of CssSelector: "css selector"
  of LinkTextSelector: "link text"
  of PartialLinkTextSelector: "partial link text"
  of TagNameSelector: "tag name"
  of XPathSelector: "xpath"

proc my() {.async.} =
  var driver = newChromeDriver()
  await driver.startSession()
  await driver.setUrl("http://www.ahszxhsd.com")
  var list = await driver.getElements(toKeyword(CssSelector),"navitem")
  echo(repr(list))
  await driver.close()

var r = my()

```

**Comment by yglukhov** [comment]
Works for me if I replace `var r = my()` with `waitFor my()`. Can you confirm?

**Comment by lihf8515** [comment]
Thank you very much.It does work.

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："Yuriy Glukhov "<notifications@github.com&gt;;
发送时间：2020年2月10日(星期一) 凌晨0:02
收件人："yglukhov/webdriver" <webdriver@noreply.github.com&gt;;
抄送："lihaifeng "<lihaifeng@wxm.com&gt;;"Author "<author@noreply.github.com&gt;;
主题：Re: [yglukhov/webdriver] Can you write a usage tutorial? (#1)
-----------------------------------

 
Works for me if I replace var r = my() with waitFor my(). Can you confirm?
