### ISSUE TITLE
 Could you consider removing "firefox.nim"

### ISSUE THREAD

**Issue by lihf8515** [yglukhov/webdriver#8]
Today, both firefox and chrome use the "W3C Webdriver" driver, while firefox proprietary drivers no longer seem to be supported, and "firefox.nim" doesn't work successfully. Could you consider removing "firefox.nim" and then changing "webdriver_base.nim" to a base class to remove "driver.nim "?

**Comment by yglukhov** [comment]
Last time i checked firefoz required geckodriver (additional software) to support W3C api, while the firefox api worked with firefox directly. Isn't it the case now?

**Comment by lihf8515** [comment]
When I first submitted the code," firefox.nim "didn't work properly, and invalid parameters were prompted when I ran.

**Comment by lihf8515** [comment]
Let me try again.
